
INSERT INTO public.assets (ticker, name, sector, asset_type, exchange, current_price, previous_close, variation, volume)
VALUES
  ('ABJC', 'ABIDJAN COTE D''IVOIRE', 'Distribution', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BICC', 'BICI COTE D''IVOIRE', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BNBC', 'BERNABE COTE D''IVOIRE', 'Distribution', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BOAB', 'BOA BURKINA FASO', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BOABF', 'BOA BURKINA FASO', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BOAC', 'BOA COTE D''IVOIRE', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BOAM', 'BOA MALI', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BOAN', 'BOA NIGER', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('BOAS', 'BOA SENEGAL', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('CABC', 'SICABLE', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('CBIBF', 'CORIS BANK INTERNATIONAL', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('CFAC', 'CFAO MOTORS COTE D''IVOIRE', 'Distribution', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('CIEC', 'CIE COTE D''IVOIRE', 'Services publics', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('ECOC', 'ECOBANK COTE D''IVOIRE', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('ETIT', 'ECOBANK TRANSNATIONAL INC', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('FTSC', 'FILTISAC', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('NEIC', 'NEI-CEDA', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('NSBC', 'NSIA BANQUE COTE D''IVOIRE', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('ONTBF', 'ONATEL BURKINA FASO', 'Télécommunications', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('ORAC', 'ORANGE COTE D''IVOIRE', 'Télécommunications', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('ORGT', 'ORAGROUP TOGO', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('PALC', 'PALM COTE D''IVOIRE', 'Agroalimentaire', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('PRSC', 'PRESCIMETAL', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SAFC', 'SAFCA', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SDCC', 'SODE COTE D''IVOIRE', 'Agroalimentaire', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SDSC', 'SDS COTE D''IVOIRE', 'Distribution', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SEMC', 'CROWN SIEM', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SGBC', 'SOCIETE GENERALE CI', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SHEC', 'VIVO ENERGY CI', 'Distribution', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SIBC', 'SIB COTE D''IVOIRE', 'Finance', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SICC', 'SICOR COTE D''IVOIRE', 'Agroalimentaire', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SLBC', 'SOLIBRA', 'Agroalimentaire', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SMBC', 'SMB', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SNTS', 'SONATEL', 'Télécommunications', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SOGC', 'SOGB', 'Agroalimentaire', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SPHC', 'SAPH', 'Agroalimentaire', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('STBC', 'SITAB', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('SVOC', 'MOVIS COTE D''IVOIRE', 'Transport', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('TTLC', 'TOTALENERGIES CI', 'Energie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('TTLS', 'TOTALENERGIES SENEGAL', 'Energie', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('UNLC', 'UNILEVER COTE D''IVOIRE', 'Agroalimentaire', 'action', 'BRVM', NULL, NULL, NULL, NULL),
  ('UNXC', 'UNIWAX', 'Industrie', 'action', 'BRVM', NULL, NULL, NULL, NULL)
ON CONFLICT (ticker) DO NOTHING;
